version: '3.1'

services:

  db:
    build: ./postgres-docker.d
    restart: always
    environment:
      POSTGRES_USER: tsundo
      POSTGRES_PASSWORD: tsundo
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
